### ISSUE TITLE
Translations not working

### ISSUE THREAD

**Issue by fede91it** [coderello/laravel-nova-lang#119]
Although in resources/lang/vendor/nova there are the files for the Italian language (folder and json), Nova keeps showing me the strings in English.

The Laravel app language is set to 'it' and the fallback language to 'en'.

What's wrong?

**Comment by hivokas** [comment]
Have you tried to clear the cache?

**Comment by fede91it** [comment]
Sure

Check that strange thing. Some string were translated (button, remember password checkbox), others no (welcome back title, etc.).

![image](https://user-images.githubusercontent.com/346224/48333498-f44c8980-e657-11e8-956a-ba2b728afa87.png)

**Comment by hivokas** [comment]
Which version of Laravel Nova do you have?

**Comment by fede91it** [comment]
The latest 1.1.7
