### ISSUE TITLE
Missing Translations (de)

### ISSUE THREAD

**Issue by StanBarrows** [coderello/laravel-nova-lang#125]
Heyho, 

First off all thanks for this package. Unfortunately I run into a couple of missing translations. Is there a way to add these translations or do I missing something?

- [ ] Ressource Title is at least in German the wrong way around (Mitglied bearbeiten)
- [ ] File not selected
- [ ] Update Ressources

<img width="1461" alt="translations" src="https://user-images.githubusercontent.com/10268813/49326450-9b835900-f552-11e8-8cc8-cd79c2b9ea49.png">

Cheers, Stan

**Comment by m-lotze** [comment]
Search is also missing from german translation.

**Comment by Dontorpedo** [comment]
also show / hide content

**Comment by Dontorpedo** [comment]
@StanBarrows 

look in your resources/lang/vendor/nova folder, you can add there missing translations or customize them

**Comment by IgorDePaula** [comment]
Resource translate title need be in same resource, this class has 2 method for this: label and singularLabel.
Like this:
https://user-images.githubusercontent.com/19389981/47080723-0bd75480-d209-11e8-9cf8-3802bc3c1d8c.png

**Comment by hivokas** [comment]
Feel free to submit the PR with the fix.
