### ISSUE TITLE
Missing Translations (nl)

### ISSUE THREAD

**Issue by LeviZandbergen** [coderello/laravel-nova-lang#130]
Hello,
I found some names that are not translated yet. The ones that i found were:

- [ ] "Search": "Zoeken",
- [ ] "Per Page": "Per Pagina",

I also think that some names are not correct:

"Create" is now "Nieuw" but then the sentence doesn't sound right. I think it needs to be "Nieuwe".

The translation of "Update" and "Edit" are the same. I think that "Bewerken" is a better translation for "Edit".

"Wachtwoordreset" between "wachtwoord" and "reset" there needs to be a space, otherwise it is not an actual word :) 

Also "Update" just doesn't sound right, for example if i want to update a user it says: "Pas aan gebruiker", that's not a correct dutch sentence. I don't know if this can be changed.

**Comment by hivokas** [comment]
Feel free to submit the PR with the fix.
