### ISSUE TITLE
Spanish Password reset button text is too long

### ISSUE THREAD

**Issue by jhm-ciberman** [coderello/laravel-nova-lang#138]
The spanish password reset button text is too long. 

The text `"Enviar Enlace Restablecimiento de contraseña"` don't fit in the button, also, it sounds weirdly translated. 
This could be replaced with simply `"Enviar enlace"` or with `"Enviar enlace de recuperación"` (That is not exactly the same but is usual in spanish websites to use the word recuperación instead of restablecimiento).

![image](https://user-images.githubusercontent.com/7988351/55438389-d2589280-5577-11e9-9e66-f1bf9f48f0c1.png)

**Comment by hivokas** [comment]
Feel free to submit PR

**Comment by jhm-ciberman** [comment]
Thanks, I will try to do it later. I'm a bit bussy this week.
