### ISSUE TITLE
Maintainer

### ISSUE THREAD

**Issue by hivokas** [coderello/laravel-nova-lang#153]
Hey @kitbs 
What do you think about becoming a maintainer?

**Comment by kitbs** [comment]
Hi @hivokas Yes, I could help out if you like.

**Comment by hivokas** [comment]
I've sent an invite.
https://github.com/coderello/laravel-nova-lang/invitations

**Comment by hivokas** [comment]
Now you can read, clone, and push to this repository. Also you can manage issues, pull requests, and some repository settings.

**Comment by hivokas** [comment]
There are few opened PRs now, feel free to manage them.

**Comment by kitbs** [comment]
Cool, I'll have a look this weekend

**Comment by hivokas** [comment]
Great work! Feel free to publish a release whenever you want.

**Comment by hivokas** [comment]
Do you have a Telegram account?

**Comment by hivokas** [comment]
It will be easier to communicate in Telegram.
My username there is the same as in GitHub.

**Comment by kitbs** [comment]
Cool, I've signed up now so I'll close this thread. :-)
