### ISSUE TITLE
Once installed, how do I select the active language?

### ISSUE THREAD

**Issue by matias2018** [coderello/laravel-nova-lang#165]
Installation instructions are straightforward. Now, once installed, how do I select the active language? 
There's a lack on the docs about how it works.
Thank you.

**Comment by kitbs** [comment]
Hi @matias2018

This package just provides the translated language string files for Nova. Functionality to select the active language is not in the scope of this package.

If you publish the languages you want for your application using our instructions, then you need to use the standard Laravel [locale configuration](https://laravel.com/docs/5.8/localization) or find another specialised package for Laravel and/or Nova which lets you switch the locale or set it based on user preferences.

**Comment by matias2018** [comment]
Hi @kitbs, thanks for the quickest reply! That's what I suspected. 
Anyway I followed your instructions and set locale to 'locale' => 'es' but nothing happened and I'm kinda stuck :(
I've set debug to active and have no errors whatsoever.
Would have any sugestion?
Thank you once again!
