### ISSUE TITLE
Unfortunately, translations for [zh‑CN] locale don't exist.

### ISSUE THREAD

**Issue by milewski** [coderello/laravel-nova-lang#166]
Hi running the following command fails, even thou zh-CN is one of the available translations on the README.md

`php artisan nova-lang:publish zh‑CN`

```
Unfortunately, translations for [zh‑CN] locale don't exist. Feel free to send a PR to add them and help other people :)
```

**Comment by kitbs** [comment]
Hi @milewski. I think I can see what's happened.

Did you copy and paste `zh‑CN` from the readme text? I used a non-breaking hyphen there for formatting reasons.

Can you try again and just type `zh-CN` with a normal hyphen when you enter the command?

If this works, I will make a small fix in the command to avoid this happening.

If not, let me know.

Thanks

**Comment by milewski** [comment]
@kitbs that was the issue, typing it manually instead of copy/paste from the docs worked 👍

**Comment by kitbs** [comment]
Glad to hear!
