### ISSUE TITLE
Validation.php Strings missing

### ISSUE THREAD

**Issue by e-reifer** [coderello/laravel-nova-lang#246]
I've been using the German translations but the Validation strings are missing.

Event the English ones are not being displayed. I just get the "validation.required" string.

I tried to change the resources/lang/de/validation.php file and add the string but that does not fix the error.
When I force publish after changes to the validation.php file, it reverts back to its previous state. 

How do I apply the German translations for the validation fields? 

Edit: If I change the locale in my config/app.php to "en", it is using the German translations for the Validation.

**Comment by kitbs** [comment]
Hallo @e-reifer 

This package only provides the validation translations for the two Laravel _Nova_ strings "attached" and "relatable" (see [validation.php](https://github.com/coderello/laravel-nova-lang/blob/1.0/resources/lang/de/validation.php)).

The file is published to `resources/lang/vendor/nova/de/validation.php`, not to `resources/lang/de/validation.php`. This package has no effect on the file you have mentioned.

You seem to be talking about the "required" etc. strings which are standard Laravel validation, and are provided by a different package: [caouecs/laravel-lang](https://github.com/caouecs/Laravel-lang).
