### ISSUE TITLE
Here is the translation for french :-)

### ISSUE THREAD

**Issue by airdev-web** [coderello/laravel-nova-lang#274]
Greetings from Belgium!

I was not able to push a new branch and so a new pull request, but here is translation for french!

`resources/lang/fr.json`

```json
{
  "novaSettings.navigationItemTitle": "Paramètres",
  "novaSettings.saveButtonText": "Sauvegarder les paramètres",
  "novaSettings.noSettingsFieldsText": "Aucun paramètre n'a été défini.",
  "novaSettings.settingsSuccessToast": "Les paramètres ont été mis à jour avec succès",
  "novaSettings.general": "Général"
}
```

**Comment by kitbs** [comment]
Bonjour @airdev-web 
I think you may have intended to submit translations for this repository: https://github.com/optimistdigital/nova-settings
Our repository is just for the core Nova language files.
Merci
