### ISSUE TITLE
[be] add translations

### ISSUE THREAD

**Issue by hivokas** [coderello/laravel-nova-lang#29]

**Comment by sebastiaanspeck** [comment]
If you mean be as Belgium, you can use the NL translations. It's 90% the same.

**Comment by hivokas** [comment]
@sebastiaanspeck no, I mean Belarusian.

**Comment by sebastiaanspeck** [comment]
Ahh. Sorry, can't help with that. Maybe it can be usefull to add in the description which language you mean

**Comment by hivokas** [comment]
https://www.w3schools.com/tags/ref_language_codes.asp
